# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "quiet" "systemd.show_status=0" "rd.udev.log_level=0" "amd_pstate=active" ];

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/629A-C79B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ {
      device = "/dev/disk/by-uuid/57df029e-4e56-499c-ae61-bc4ee126a7a3";
      options = [ "discard" ];
    } ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/53039a3e-005b-4479-a53c-c4eb72033dd0";
      fsType = "ext4";
      options = [ "relatime" "commit=60" ];
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/3D6EBEC95D9AB4A0";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" "gid=100" "umask=0022" "prealloc" "nofail" "relatime" ];
    };


  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
